### ISSUE TITLE
NavBar: Remove links and transfer functionality to tabs

### ISSUE THREAD

**Issue by 123vivekr** [123vivekr/OpenSalve-Web#7]
Currently linking is done by the ```<Link>``` component.
Replace the Link logic with button functions.

**Comment by aswinmprabhu** [comment]
Not buttons. Make them tabs.
Like Whatsapp Android app.

**Comment by 123vivekr** [comment]
Closed by https://github.com/123vivekr/OpenSalve-Web/pull/8
